import { DeviconSetup } from '../models';

export const mainTechnologies: DeviconSetup[] = [
  {
    technology: 'Angular',
    iconName: 'angularjs',
    sufix: 'plain',
    colored: true,
    wordmark: false,
  },
  {
    technology: 'NodeJS',
    iconName: 'nodejs',
    sufix: 'plain',
    colored: true,
    wordmark: false,
  },
  {
    technology: 'ExpressJS',
    iconName: 'express',
    sufix: 'original',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'MongoDB',
    iconName: 'mongodb',
    sufix: 'plain',
    colored: true,
    wordmark: false,
  },
  {
    technology: 'Html5',
    iconName: 'html5',
    sufix: 'plain',
    colored: true,
    wordmark: false,
  },
  {
    technology: 'Css3',
    iconName: 'css3',
    sufix: 'plain',
    colored: true,
    wordmark: false,
  },
  {
    technology: 'Typescript',
    iconName: 'typescript',
    sufix: 'plain',
    colored: true,
    wordmark: false,
  },
];

export const otherTechnologies: DeviconSetup[] = [
  {
    technology: 'React',
    iconName: 'react',
    sufix: 'original',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Redux',
    iconName: 'redux',
    sufix: 'original',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'NextJS',
    iconName: 'nextjs',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Webpack',
    iconName: 'webpack',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'NestJS',
    iconName: 'nestjs',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Docker',
    iconName: 'docker',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Git',
    iconName: 'git',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Github',
    iconName: 'github',
    sufix: 'original',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Gitlab',
    iconName: 'gitlab',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Bitbucket',
    iconName: 'bitbucket',
    sufix: 'original',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Bamboo',
    iconName: 'bamboo',
    sufix: 'original',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Bootstrap',
    iconName: 'bootstrap',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Grafana',
    iconName: 'grafana',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Graphql',
    iconName: 'graphql',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Jira',
    iconName: 'jira',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Jest',
    iconName: 'jest',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Mocha',
    iconName: 'mocha',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'NPM',
    iconName: 'npm',
    sufix: 'original',
    colored: false,
    wordmark: true,
  },
  {
    technology: 'mySQL',
    iconName: 'mysql',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'PostgreSQL',
    iconName: 'postgresql',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Sqlite',
    iconName: 'sqlite',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Sequelize',
    iconName: 'sequelize',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Less',
    iconName: 'less',
    sufix: 'plain',
    colored: false,
    wordmark: true,
  },
  {
    technology: 'Sass',
    iconName: 'sass',
    sufix: 'original',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'MaterialUI',
    iconName: 'materialui',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Tailwindcss',
    iconName: 'tailwindcss',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
  {
    technology: 'Figma',
    iconName: 'figma',
    sufix: 'plain',
    colored: false,
    wordmark: false,
  },
];
