export enum Technologies {
  TYPESCRIPT = 'typescript',
  ANGULAR = 'angular',
  NODEJS = 'nodeJS',
  EXPRESS = 'express',
  BAMBOO = 'bamboo',
  VERACODE = 'veracode',
  AWS = 'aws',
  GIT = 'git',
  BITBUCKET = 'bitbucket',
  JIRA = 'jira',
  GITLAB = 'gitLab',
  TAILWIND = 'tailwind',
  BOOSTRAP = 'boostrap',
  SWAGGER = 'swagger',
  INVERSIFY = 'inversify',
  KEYCLOAK = 'keycloak',
  FIREBASE = 'firebase',
  ELASTICSEARCH = 'elasticSearch',
  TRELLO = 'trello',
}
